const FONT_COLOR = "#20232A";
const MAIN_COLOR = "#F4F4EF";
const HIGHT_LIGHT_COLOR = "#A01D26";
const SUB_COLOR = "#D1DAD7";
const MAIN_FONT_SIZE = 18;
const SECTION_TITLE_FONT_SIZE = 21;
const MAIN_FONT_FAMILY = "'Noto Sans JP', sans-serif";
const MAIN_FONT_WIGHT = 400;
const BOLD_FONT_WIGHT = 500;

export {
  FONT_COLOR,
  MAIN_COLOR,
  HIGHT_LIGHT_COLOR,
  SUB_COLOR,
  MAIN_FONT_SIZE,
  SECTION_TITLE_FONT_SIZE,
  MAIN_FONT_FAMILY,
  MAIN_FONT_WIGHT,
  BOLD_FONT_WIGHT,
};
